services:
    mysql:
        image: mysql:8.0
        container_name: fruitsflow_database
        restart: always
        env_file:
            - .env.docker
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: fruitsflow_phpmyadmin
        restart: always
        ports:
            - "8081:80"
        env_file:
            - .env.docker
        depends_on:
            - mysql

    server:
        build:
            context: ./Server
        container_name: fruitsflow_server
        ports:
            - "8080:8080"
        volumes:
            -   ./Server/uploads:/app/uploads
        env_file:
            - .env.docker
        depends_on:
            - mysql

    website:
        build:
            context: ./Website
        container_name: fruitsflow_website
        ports:
            - "3000:3000"
        volumes:
            -   ./Website/public:/app/public
        env_file:
            - .env.docker
        depends_on:
            - server

volumes:
  mysql_data: {}